# Generated by Django 4.2.2 on 2023-06-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='End',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendar',
            name='Start',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='partmaintenance',
            name='DueDate',
            field=models.DateField(),
        ),
    ]
