# Generated by Django 4.2.2 on 2023-06-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planemaintenance',
            unique_together={('PlaneSN', 'MDS', 'JST')},
        ),
    ]
