# Generated by Django 4.2.2 on 2023-07-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='Aircraft',
        ),
        migrations.AddField(
            model_name='calendar',
            name='MDS',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendar',
            name='TailNumber',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
