# Generated by Django 4.2.2 on 2023-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='MDS',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='resource',
            unique_together={('TailNumber', 'MDS', 'GeoLoc')},
        ),
    ]
