# Generated by Django 4.2.2 on 2023-07-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partmaintenance',
            name='Scheduled',
        ),
        migrations.RemoveField(
            model_name='planemaintenance',
            name='Scheduled',
        ),
    ]
