# Generated by Django 4.2.2 on 2023-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaintenance',
            name='Scheduled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='planemaintenance',
            name='Scheduled',
            field=models.BooleanField(default=True),
        ),
    ]
