# Generated by Django 4.2.2 on 2023-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0002_alter_partmaintenance_scheduled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partmaintenance',
            name='Scheduled',
        ),
        migrations.RemoveField(
            model_name='planemaintenance',
            name='Scheduled',
        ),
    ]
