# Generated by Django 4.2.2 on 2023-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0002_calendar_delete_calender_partmaintenance_duedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaintenance',
            name='MDS',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='partmaintenance',
            name='PlaneSN',
            field=models.CharField(max_length=10),
        ),
    ]
