# Generated by Django 4.2.2 on 2023-07-07 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0003_calendar_resourceid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('ResourceID', models.AutoField(primary_key=True, serialize=False)),
                ('TailNumber', models.CharField(max_length=10)),
            ],
        ),
    ]
