# Generated by Django 4.2.2 on 2023-07-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0004_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='GeoLoc',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
