# Generated by Django 4.2.2 on 2023-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0004_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partmaintenance',
            name='E_F',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='planemaintenance',
            name='E_F',
            field=models.CharField(max_length=10),
        ),
    ]
