# Generated by Django 4.2.2 on 2023-07-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ROUSApp', '0005_alter_partmaintenance_e_f_alter_planemaintenance_e_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='Completed',
            field=models.BooleanField(default=False),
        ),
    ]
